<?php
/**
* Application settings.
* Make a copy of this file, fill in application values in that file.
* Rename the new file to settings.php
* Do not edit this file.
*/

	/**
	* Main Database (Postgresql)
	*/
	$global_db_username		=	"";
	$global_db_password		=	"";
	$global_db_host			=	"";
	$global_db_name			=	"";
	$global_db_port			=	"";

	/**
	* Secondary Database (Mysql)
	* Data will be synced between Mysql and Postgresql
	*/
	$mydbname				=	"";
	$mydbuser				=	"";
	$mydbpass				=	"";
	$mydbhost				=	"";
?>
