<?php
/**
* Application settings.
* Make a copy of this file, fill in application values in that file.
* Rename the new file to settings.php
* Do not edit this file.
*/

	$global_db_username		=	"";
	$global_db_password		=	"";
	$global_db_host			=	"";
	$global_db_name			=	"";
?>
